In [20]:
import pandas as pd
import numpy as np

year_used = "2016"
columns = ["State",year_used]

In [21]:
#Political Factor DataFrame (based on Popular Vote in 2016 Presidental Election)
election2016_file = "Resources/2016/data/election_2016.csv"
election2016_data =  pd.read_csv(election2016_file)
election2016_data = pd.DataFrame(election2016_data)
gov_election2016_data = election2016_data.copy()
gov_election2016_data = gov_election2016_data.iloc[:56,:4] 
convert_to_number_list = ["Democratic Candidates","Republican Candidates","Other Candidates"]
for item in ["Democratic Candidates","Republican Candidates","Other Candidates"]:
    for x in range(len(gov_election2016_data[item])):
        gov_election2016_data[item][x] = int(gov_election2016_data[item][x].replace(',' , ''))
    
us_states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}
gov_election2016_data["Party"] = gov_election2016_data["State"]
for state in range(len(gov_election2016_data["State"])):
    try:
        if gov_election2016_data.iloc[state,1] > gov_election2016_data.iloc[state,2]:
            if gov_election2016_data.iloc[state,1] > gov_election2016_data.iloc[state,3]:
                gov_election2016_data.iloc[state, 4] = "D"
        elif gov_election2016_data.iloc[state,2] > gov_election2016_data.iloc[state,1]:
            if gov_election2016_data.iloc[state,2] > gov_election2016_data.iloc[state,3]:
                gov_election2016_data.iloc[state, 4] = "R"
        else:
            gov_election2016_data.iloc[state, 4] = "I"
        gov_election2016_data["State"][state] = us_states[gov_election2016_data["State"][state]]
    except:
        None
gov_election2016_data = gov_election2016_data[["State","Party"]]
gov_election2016_data.to_csv("output/gov_election2016.csv", index=False, header=True)
gov_election2016_data

                       State Party
0                    Alabama     R
1                     Alaska     R
2             American Samoa     R
3                    Arizona     R
4                   Arkansas     R
5                 California     D
6                   Colorado     D
7                Connecticut     D
8                   Delaware     D
9       District of Columbia     D
10                   Florida     R
11                   Georgia     R
12                      Guam     D
13                    Hawaii     D
14                     Idaho     R
15                  Illinois     D
16                   Indiana     R
17                      Iowa     R
18                    Kansas     R
19                  Kentucky     R
20                 Louisiana     R
21                     Maine     D
22                  Maryland     D
23             Massachusetts     D
24                  Michigan     R
25                 Minnesota     D
26               Mississippi     R
27                  Missouri     R
28                   Montana     R
29                  Nebraska     R
30                    Nevada     D
31             New Hampshire     D
32                New Jersey     D
33                New Mexico     D
34                  New York     D
35            North Carolina     R
36              North Dakota     R
37  Northern Mariana Islands     I
38                      Ohio     R
39                  Oklahoma     R
40                    Oregon     D
41              Pennsylvania     R
42               Puerto Rico     I
43              Rhode Island     D
44            South Carolina     R
45              South Dakota     R
46                 Tennessee     R
47                     Texas     R
48                      Utah     R
49                   Vermont     D
50            Virgin Islands     D
51                  Virginia     D
52                Washington     D
53             West Virginia     R
54                 Wisconsin     R
55                   Wyoming     R

In [30]:
#Education Attainment Population Data Cleanup to DataFrame
education_file = f"Resources/{year_used}/data/education_{year_used}.csv"
education_data = pd.read_csv(education_file)
education_data_file = education_data.copy()

#S1501_C02_015E Percentage of Bachelor Degree Holders
data_columns = ["NAME","S1501_C02_015E"]
education_data_file = education_data_file[data_columns]
education_data_file = education_data_file.iloc[1:,:]
for column in data_columns:
    try:
        education_data_file[column] = education_data_file[column].astype(np.float64)
    except ValueError:
        None
education_data_file = education_data_file.rename(columns={"NAME":"State",
                                                          data_columns[1]:f"{year_used}"})
education_data_file = pd.merge(education_data_file,gov_election2016_data, on="State")
education_data_file = education_data_file.sort_values(year_used, ascending=True)
education_data_file = education_data_file.reset_index(drop=True)
education_data_file.to_csv(f"output/pop_education_{year_used}.csv", index=False, header=True)
education_data_file

                   State  2016 Party
0          West Virginia  20.8     R
1            Mississippi  21.8     R
2               Arkansas  22.4     R
3              Louisiana  23.4     R
4               Kentucky  23.4     R
5                 Nevada  23.5     D
6                Alabama  24.7     R
7               Oklahoma  25.2     R
8            Puerto Rico  25.3     I
9                Indiana  25.6     R
10             Tennessee  26.1     R
11               Wyoming  27.1     R
12        South Carolina  27.2     R
13            New Mexico  27.2     D
14                  Ohio  27.5     R
15                 Idaho  27.6     R
16              Michigan  28.3     R
17                  Iowa  28.4     R
18              Missouri  28.5     R
19               Florida  28.6     R
20          South Dakota  28.9     R
21               Arizona  28.9     R
22                 Texas  28.9     R
23             Wisconsin  29.5     R
24                Alaska  29.6     R
25          North Dakota  29.6     R
26                 Maine  30.1     D
27        North Carolina  30.4     R
28               Georgia  30.5     R
29          Pennsylvania  30.8     R
30               Montana  31.0     R
31              Delaware  31.0     D
32              Nebraska  31.4     R
33                Hawaii  31.9     D
34                  Utah  32.6     R
35                Oregon  32.7     D
36                Kansas  32.8     R
37            California  32.9     D
38              Illinois  34.0     D
39          Rhode Island  34.1     D
40             Minnesota  34.8     D
41            Washington  35.1     D
42              New York  35.7     D
43               Vermont  36.4     D
44         New Hampshire  36.6     D
45              Virginia  38.1     D
46            New Jersey  38.6     D
47           Connecticut  38.6     D
48              Maryland  39.3     D
49              Colorado  39.9     D
50         Massachusetts  42.7     D
51  District of Columbia  56.8     D

In [83]:
#Suicide Rate Population Data Cleanup to DataFrame
suicide_file = f"Resources/All/data/suicide_2005-2017.csv"
suicide_data = pd.read_csv(suicide_file)
suicide_data_file = suicide_data.copy()
suicide_data_file
#Suicide Rate (per 100,000) by State
data_columns = ["STATE","RATE"]
data_labels = ["State", f"{year_used}"]
indexes = []
for row in range(len(suicide_data_file["STATE"])):
    if suicide_data_file.iloc[row,0] == int(year_used):
        indexes.append(row)
suicide_data_file = suicide_data_file.loc[indexes]        
suicide_data_file = suicide_data_file.reset_index(drop=True)
suicide_data_file = suicide_data_file[data_columns]

for column in data_columns:
    try:
        suicide_data_file[column] = suicide_data_file[column].astype(np.float64)
    except ValueError:
        None
for row in range(len(suicide_data_file["STATE"])):
    suicide_data_file[data_columns[0]][row]=us_states[suicide_data_file[data_columns[0]][row]]
    suicide_data_file[data_columns[1]][row]=100*suicide_data_file[data_columns[1]][row]/suicide_data_file[data_columns[1]].sum()
suicide_data_file = suicide_data_file.rename(columns={data_columns[0]:data_labels[0],
                                                      data_columns[1]:data_labels[1]})
suicide_data_file = pd.merge(suicide_data_file,gov_election2016_data, on="State")
suicide_data_file = suicide_data_file.sort_values(year_used, ascending=True)
suicide_data_file = suicide_data_file.reset_index(drop=True)
suicide_data_file.to_csv(f"output/pop_suicide_{year_used}.csv", index=False, header=True)
suicide_data_file

C:\Users\Michelle\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Michelle\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

             State       2016 Party
0      Connecticut   1.451866     D
1       California   1.453632     D
2    Massachusetts   1.658987     D
3         Delaware   1.673924     D
4         Illinois   1.710293     D
5       New Jersey   1.728336     D
6         Maryland   1.746896     D
7           Hawaii   1.850298     D
8          Alabama   1.988349     R
9          Georgia   1.999249     R
10        New York   2.055384     D
11         Florida   2.067390     R
12         Arizona   2.349307     R
13            Iowa   2.418294     R
14        Arkansas   2.465915     R
15         Indiana   2.497430     R
16       Louisiana   2.523148     R
17     Mississippi   2.530284     R
18        Michigan   2.541548     R
19       Minnesota   2.575386     D
20        Nebraska   2.868902     R
21        Colorado   2.874037     D
22           Maine   2.885076     D
23        Kentucky   2.913249     R
24          Kansas   3.025950     R
25           Idaho   3.324534     R
26          Alaska   3.325221     R
27  North Carolina   3.350150     R
28    Rhode Island   3.541018     D
29        Missouri   3.741737     R
30            Ohio   3.896670     R
31   New Hampshire   4.002014     D
32    Pennsylvania   4.502423     R
33           Texas   4.598094     R
34          Nevada   4.794018     D
35    North Dakota   5.021242     R
36  South Carolina   5.086927     R
37          Oregon   5.250107     D
38         Montana   5.428722     R
39        Virginia   5.455152     D
40      New Mexico   5.472935     D
41       Tennessee   5.727352     R
42        Oklahoma   5.930354     R
43      Washington   6.361317     D
44    South Dakota   6.778041     R
45       Wisconsin   6.839082     R
46         Vermont   6.853672     D
47            Utah   8.194728     R
48   West Virginia   8.551570     R
49         Wyoming  12.169198     R

In [65]:
#Population Data Cleanup to DataFrame
file = "Resources/ALL/data/population2010-2019.csv"
total_population_data_file_all = pd.read_csv(file)
total_population_data_file = total_population_data_file_all.copy()
total_population_data_file = total_population_data_file.iloc[5:,4:17]
total_population_data_file = total_population_data_file.reset_index()
total_population_data_file = total_population_data_file.iloc[:,1:]
total_population_data_file = total_population_data_file.rename(columns={"NAME":"State"})
total_population_data_file = total_population_data_file.rename(columns={f"POPESTIMATE{year_used}":f"{year_used}"})
total_population_data_file = total_population_data_file.loc[:,columns]
total_population_data_file = total_population_data_file.iloc[:51]
total_population_data_file.dtypes
total_population_data_file = pd.merge(total_population_data_file,gov_election2016_data, on="State")
total_population_data_file

                   State      2016 Party
0                Alabama   4863525     R
1                 Alaska    741456     R
2                Arizona   6941072     R
3               Arkansas   2989918     R
4             California  39167117     D
5               Colorado   5539215     D
6            Connecticut   3578141     D
7               Delaware    948921     D
8   District of Columbia    685815     D
9                Florida  20613477     R
10               Georgia  10301890     R
11                Hawaii   1427559     D
12                 Idaho   1682380     R
13              Illinois  12820527     D
14               Indiana   6634304     R
15                  Iowa   3131371     R
16                Kansas   2910844     R
17              Kentucky   4438182     R
18             Louisiana   4678135     R
19                 Maine   1331317     D
20              Maryland   6003323     D
21         Massachusetts   6823608     D
22              Michigan   9950571     R
23             Minnesota   5522744     D
24           Mississippi   2987938     R
25              Missouri   6087135     R
26               Montana   1040859     R
27              Nebraska   1905616     R
28                Nevada   2917563     D
29         New Hampshire   1342307     D
30            New Jersey   8870827     D
31            New Mexico   2091630     D
32              New York  19633428     D
33        North Carolina  10154788     R
34          North Dakota    754434     R
35                  Ohio  11634370     R
36              Oklahoma   3926331     R
37                Oregon   4089976     D
38          Pennsylvania  12782275     R
39          Rhode Island   1056770     D
40        South Carolina   4957968     R
41          South Dakota    862996     R
42             Tennessee   6646010     R
43                 Texas  27914410     R
44                  Utah   3041868     R
45               Vermont    623657     D
46              Virginia   8410106     D
47            Washington   7294771     D
48         West Virginia   1831023     R
49             Wisconsin   5772628     R
50               Wyoming    584215     R

In [24]:
#Veteran Population Data Cleanup to DataFrame
veteran_file = f"Resources/{year_used}/data/veteran_{year_used}.csv"
veteran_data = pd.read_csv(veteran_file)
veteran_data_file = veteran_data.copy()
#S2101_C01_001E Population Data
#S2101_C03_001E Veteran Data
data_columns = ["NAME","S2101_C01_001E","S2101_C03_001E"]
veteran_data_file = veteran_data_file[data_columns]
veteran_data_file = veteran_data_file.iloc[1:,:]
for column in data_columns:
    try:
        veteran_data_file[column] = veteran_data_file[column].astype(np.float64)
    except ValueError:
        None
veteran_data_file[year_used] = 100*veteran_data_file[data_columns[2]]/veteran_data_file[data_columns[1]]
veteran_data_file = veteran_data_file.rename(columns={"NAME":"State"})
veteran_data_file = veteran_data_file[columns]
veteran_data_file = pd.merge(veteran_data_file,gov_election2016_data, on="State")
veteran_data_file = veteran_data_file.sort_values(year_used, ascending=True)
veteran_data_file = veteran_data_file.reset_index(drop=True)
veteran_data_file.to_csv(f"output/pop_veteran_{year_used}.csv", index=False, header=True)
veteran_data_file

                   State       2016 Party
0            Puerto Rico   2.929305     I
1               New York   4.655143     D
2   District of Columbia   4.729473     D
3             New Jersey   4.758632     D
4             California   5.409096     D
5          Massachusetts   5.733040     D
6                   Utah   5.774948     R
7               Illinois   5.922270     D
8            Connecticut   6.067437     D
9           Rhode Island   6.568523     D
10             Louisiana   6.797984     R
11                 Texas   7.131418     R
12              Michigan   7.230487     R
13             Minnesota   7.348978     D
14               Vermont   7.402205     D
15             Wisconsin   7.494950     R
16               Indiana   7.542941     R
17                  Iowa   7.639683     R
18          Pennsylvania   7.831891     R
19           Mississippi   7.839471     R
20              Maryland   7.980993     D
21              Kentucky   8.001631     R
22                Kansas   8.054237     R
23                  Ohio   8.108974     R
24          North Dakota   8.133105     R
25               Georgia   8.303860     R
26             Tennessee   8.346628     R
27              Nebraska   8.444477     R
28              Delaware   8.495382     D
29        North Carolina   8.573553     R
30              Arkansas   8.687526     R
31               Florida   8.712901     R
32               Alabama   8.827733     R
33              Colorado   8.859481     D
34                 Idaho   8.893512     R
35              Missouri   8.973662     R
36            New Mexico   8.986301     D
37         New Hampshire   9.126465     D
38                Oregon   9.180491     D
39               Arizona   9.182420     R
40                Nevada   9.231479     D
41              Oklahoma   9.360326     R
42          South Dakota   9.451474     R
43         West Virginia   9.490865     R
44            Washington   9.573170     D
45                 Maine   9.579285     D
46        South Carolina   9.599287     R
47                Hawaii   9.674123     D
48              Virginia  10.435427     D
49               Montana  10.539876     R
50               Wyoming  10.748445     R
51                Alaska  12.213063     R