In [3]:
import pandas as pd
import numpy as np
import time

In [4]:
#Population Data to DataFrame (named test_total_population_data)
file = "Resources/ALL/data/population2010-2019.csv"
total_population_data_file_all = pd.read_csv(file)
total_population_data_file = total_population_data_file_all.copy()
total_population_data_file = total_population_data_file.iloc[5:,4:17]
total_population_data_file = total_population_data_file.reset_index()
total_population_data_file = total_population_data_file.iloc[:,1:]
total_population_data_file = total_population_data_file.rename(columns={"NAME":"state"})
years = ["state"]
for year in range(2015,2019,1):
    total_population_data_file = total_population_data_file.rename(columns={f"POPESTIMATE{year}":f"{year}"})
    years.append(str(year))
total_population_data_file = total_population_data_file.loc[:,years]
total_population_data_file = total_population_data_file.iloc[:51]
total_population_data_file.dtypes
total_population_data_file

                   state      2015      2016      2017      2018
0                Alabama   4852347   4863525   4874486   4887681
1                 Alaska    737498    741456    739700    735139
2                Arizona   6829676   6941072   7044008   7158024
3               Arkansas   2978048   2989918   3001345   3009733
4             California  38918045  39167117  39358497  39461588
5               Colorado   5450623   5539215   5611885   5691287
6            Connecticut   3587122   3578141   3573297   3571520
7               Delaware    941252    948921    956823    965479
8   District of Columbia    675400    685815    694906    701547
9                Florida  20209042  20613477  20963613  21244317
10               Georgia  10178447  10301890  10410330  10511131
11                Hawaii   1422052   1427559   1424393   1420593
12                 Idaho   1651059   1682380   1717715   1750536
13              Illinois  12858913  12820527  12778828  12723071
14               Indiana   6608422   6634304   6658078   6695497
15                  Iowa   3120960   3131371   3141550   3148618
16                Kansas   2909011   2910844   2908718   2911359
17              Kentucky   4425976   4438182   4452268   4461153
18             Louisiana   4664628   4678135   4670560   4659690
19                 Maine   1328262   1331317   1334612   1339057
20              Maryland   5985562   6003323   6023868   6035802
21         Massachusetts   6794228   6823608   6859789   6882635
22              Michigan   9931715   9950571   9973114   9984072
23             Minnesota   5482032   5522744   5566230   5606249
24           Mississippi   2988471   2987938   2988510   2981020
25              Missouri   6071732   6087135   6106670   6121623
26               Montana   1030475   1040859   1052482   1060665
27              Nebraska   1891277   1905616   1915947   1925614
28                Nevada   2866939   2917563   2969905   3027341
29         New Hampshire   1336350   1342307   1348787   1353465
30            New Jersey   8867949   8870827   8885525   8886025
31            New Mexico   2089291   2091630   2091784   2092741
32              New York  19654666  19633428  19589572  19530351
33        North Carolina  10031646  10154788  10268233  10381615
34          North Dakota    754066    754434    754942    758080
35                  Ohio  11617527  11634370  11659650  11676341
36              Oklahoma   3909500   3926331   3931316   3940235
37                Oregon   4015792   4089976   4143625   4181886
38          Pennsylvania  12784826  12782275  12787641  12800922
39          Rhode Island   1056065   1056770   1055673   1058287
40        South Carolina   4891938   4957968   5021268   5084156
41          South Dakota    853988    862996    872868    878698
42             Tennessee   6591170   6646010   6708799   6771631
43                 Texas  27470056  27914410  28295273  28628666
44                  Utah   2981835   3041868   3101042   3153550
45               Vermont    625216    623657    624344    624358
46              Virginia   8361808   8410106   8463587   8501286
47            Washington   7163657   7294771   7423362   7523869
48         West Virginia   1842050   1831023   1817004   1804291
49             Wisconsin   5760940   5772628   5790186   5807406
50               Wyoming    585613    584215    578931    577601

In [14]:
#GDP Data to DataFrame (note:measure in millions of dollars)
file = "Resources/ALL/data/gdp2010-2019.csv"
gdp_data_file_all = pd.read_csv(file)
gdp_data_file = gdp_data_file_all.copy()
num_of_indexes = int(gdp_data_file["GeoName"].count())
indexes = []
gdp_data_file = gdp_data_file.rename(columns={"GeoName":"state"})
for index in range(num_of_indexes):
    if gdp_data_file.loc[index,"Description"] == "All industry total":
        indexes.append(index)
gdp_data_file = gdp_data_file.iloc[indexes]
gdp_data_file = gdp_data_file.iloc[:52]
gdp_data_file = gdp_data_file.reset_index()
gdp_data_file = gdp_data_file.loc[:,years]
for year in years:
    try:
        gdp_data_file[year] = gdp_data_file[year].astype(np.float64)
    except ValueError:
        None

gdp_data_file.to_csv("output/econ_gdp.csv", index=False, header=True)
gdp_data_file.dtypes
gdp_data_file

                   state        2015        2016        2017        2018
0        United States *  18224780.0  18715040.0  19519424.0  20580223.0
1                Alabama    200402.7    203829.8    210364.4    221735.5
2                 Alaska     50641.6     49363.4     51803.1     54734.1
3                Arizona    297141.2    311091.0    327495.8    348297.1
4               Arkansas    118761.2    120374.8    123383.1    128418.9
5             California   2553772.2   2657797.6   2819110.7   2997732.8
6               Colorado    318554.9    329368.3    350004.4    371749.6
7            Connecticut    260072.6    263696.4    268310.5    275726.9
8               Delaware     70969.4     69549.7     70774.8     73481.3
9   District of Columbia    125211.9    129826.1    134042.7    140660.9
10               Florida    895146.2    938774.2    985665.4   1039236.4
11               Georgia    513565.6    539525.1    566473.6    592153.4
12                Hawaii     82710.0     85843.8     89428.9     93797.9
13                 Idaho     66004.3     69029.4     72723.2     77052.0
14              Illinois    792999.4    806315.5    826817.8    865310.4
15               Indiana    330032.2    338126.1    351105.6    366800.5
16                  Iowa    178472.6    179546.6    181846.3    189701.6
17                Kansas    152374.1    156857.4    161219.6    168318.0
18              Kentucky    191923.3    195342.2    200715.4    208087.5
19             Louisiana    234299.1    227226.7    239204.3    257287.8
20                 Maine     57525.7     59753.9     62040.3     64856.0
21              Maryland    367096.5    384889.1    394258.6    412584.2
22         Massachusetts    502858.0    519407.6    540786.0    569488.0
23              Michigan    474301.4    491774.2    505561.2    527095.8
24             Minnesota    329493.2    339100.1    351416.8    368852.4
25           Mississippi    105883.4    107096.6    110223.4    114834.2
26              Missouri    294794.6    297582.6    304946.2    318921.0
27               Montana     46152.9     45457.9     47559.1     50326.6
28              Nebraska    115328.0    116193.8    120517.4    123977.9
29                Nevada    144232.4    151215.1    158847.6    169309.9
30         New Hampshire     76033.3     78477.9     80900.2     84463.9
31            New Jersey    569679.5    582427.5    595324.5    622002.8
32            New Mexico     90969.0     91043.6     94267.1    100296.8
33              New York   1487754.1   1539555.2   1604133.6   1668866.2
34        North Carolina    503628.8    519122.1    538401.6    563690.5
35          North Dakota     55012.2     50833.1     52472.3     56082.3
36                  Ohio    610772.3    622835.2    645326.0    675905.2
37              Oklahoma    185936.7    178913.2    188368.1    202554.1
38                Oregon    203158.9    215050.4    226618.9    239782.8
39          Pennsylvania    711205.4    726163.9    744290.1    783167.8
40          Rhode Island     56759.4     57693.9     58506.3     60587.6
41        South Carolina    203920.9    212987.4    223111.1    233929.9
42          South Dakota     47752.3     48606.1     49738.7     52014.9
43             Tennessee    322663.6    335025.7    345949.8    364104.9
44                 Texas   1568457.0   1565632.2   1665631.8   1802511.2
45                  Utah    149371.6    157883.3    167254.6    178137.6
46               Vermont     30729.6     31659.0     32209.8     33256.3
47              Virginia    484216.6    493877.9    509372.8    532892.5
48            Washington    470329.3    491358.2    524814.6    565831.0
49         West Virginia     70281.0     69721.4     73162.9     77437.6
50             Wisconsin    305816.5    313532.4    321987.7    336294.0
51               Wyoming     37721.5     35740.3     37453.6     39118.5

In [13]:
#GDP per capita Data to DataFrame
gdppercapita_data_file = gdp_data_file.copy()
gdppercapita_data_file = gdppercapita_data_file.merge(total_population_data_file, on="state")
years_only = years[1:]
for year in years_only:
    gdppercapita_data_file[year] = gdppercapita_data_file[f"{year}_x"]/gdppercapita_data_file[f"{year}_y"]
gdppercapita_data_file = gdppercapita_data_file[years]

gdppercapita_data_file.to_csv("output/econ_gdppercapita.csv", index=False, header=True)
gdppercapita_data_file.dtypes
gdppercapita_data_file

                   state      2015      2016      2017      2018
0                Alabama  0.041300  0.041910  0.043156  0.045366
1                 Alaska  0.068667  0.066576  0.070033  0.074454
2                Arizona  0.043507  0.044819  0.046493  0.048658
3               Arkansas  0.039879  0.040260  0.041109  0.042668
4             California  0.065619  0.067858  0.071626  0.075966
5               Colorado  0.058444  0.059461  0.062368  0.065319
6            Connecticut  0.072502  0.073696  0.075088  0.077202
7               Delaware  0.075399  0.073293  0.073969  0.076109
8   District of Columbia  0.185389  0.189302  0.192893  0.200501
9                Florida  0.044294  0.045542  0.047018  0.048918
10               Georgia  0.050456  0.052371  0.054415  0.056336
11                Hawaii  0.058162  0.060133  0.062784  0.066027
12                 Idaho  0.039977  0.041031  0.042337  0.044016
13              Illinois  0.061669  0.062893  0.064702  0.068011
14               Indiana  0.049941  0.050966  0.052734  0.054783
15                  Iowa  0.057185  0.057338  0.057884  0.060249
16                Kansas  0.052380  0.053887  0.055426  0.057814
17              Kentucky  0.043363  0.044014  0.045082  0.046644
18             Louisiana  0.050229  0.048572  0.051215  0.055216
19                 Maine  0.043309  0.044883  0.046486  0.048434
20              Maryland  0.061330  0.064113  0.065449  0.068356
21         Massachusetts  0.074013  0.076119  0.078834  0.082743
22              Michigan  0.047756  0.049422  0.050692  0.052794
23             Minnesota  0.060104  0.061401  0.063134  0.065793
24           Mississippi  0.035431  0.035843  0.036882  0.038522
25              Missouri  0.048552  0.048887  0.049937  0.052097
26               Montana  0.044788  0.043673  0.045188  0.047448
27              Nebraska  0.060979  0.060974  0.062902  0.064384
28                Nevada  0.050309  0.051829  0.053486  0.055927
29         New Hampshire  0.056896  0.058465  0.059980  0.062406
30            New Jersey  0.064240  0.065657  0.066999  0.069998
31            New Mexico  0.043541  0.043528  0.045065  0.047926
32              New York  0.075695  0.078415  0.081887  0.085450
33        North Carolina  0.050204  0.051121  0.052434  0.054297
34          North Dakota  0.072954  0.067379  0.069505  0.073979
35                  Ohio  0.052573  0.053534  0.055347  0.057887
36              Oklahoma  0.047560  0.045568  0.047915  0.051407
37                Oregon  0.050590  0.052580  0.054691  0.057338
38          Pennsylvania  0.055629  0.056810  0.058204  0.061181
39          Rhode Island  0.053746  0.054595  0.055421  0.057251
40        South Carolina  0.041685  0.042959  0.044433  0.046012
41          South Dakota  0.055917  0.056323  0.056983  0.059195
42             Tennessee  0.048954  0.050410  0.051567  0.053769
43                 Texas  0.057097  0.056087  0.058866  0.062962
44                  Utah  0.050094  0.051903  0.053935  0.056488
45               Vermont  0.049150  0.050763  0.051590  0.053265
46              Virginia  0.057908  0.058724  0.060184  0.062684
47            Washington  0.065655  0.067358  0.070698  0.075205
48         West Virginia  0.038154  0.038078  0.040266  0.042919
49             Wisconsin  0.053084  0.054314  0.055609  0.057908
50               Wyoming  0.064414  0.061177  0.064694  0.067726

In [12]:
#Personal Consumption Per Capita to DataFrame (note:measure in dollars)
file = "Resources/ALL/data/personalconsumptionpercapita1997_2018.csv"
personalconsumptionpercapita_data_file_all = pd.read_csv(file)
allpersonalconsumptionpercapita_data_file = personalconsumptionpercapita_data_file_all.copy()
num_of_indexes = int(allpersonalconsumptionpercapita_data_file["GeoName"].count())
indexes = []
allpersonalconsumptionpercapita_data_file = allpersonalconsumptionpercapita_data_file.rename(columns={"GeoName":"state"})
for index in range(num_of_indexes):
    if allpersonalconsumptionpercapita_data_file.loc[index,"Description"] == "Per capita personal consumption expenditures":
        indexes.append(index)
allpersonalconsumptionpercapita_data_file = allpersonalconsumptionpercapita_data_file.iloc[indexes]
allpersonalconsumptionpercapita_data_file = allpersonalconsumptionpercapita_data_file.reset_index()
allpersonalconsumptionpercapita_data_file = allpersonalconsumptionpercapita_data_file.iloc[:52]
allpersonalconsumptionpercapita_data_file = allpersonalconsumptionpercapita_data_file.loc[:,years]
for year in years:
    try:
        gdp_data_file[year] = gdp_data_file[year].astype(np.float64)
    except ValueError:
        None
allpersonalconsumptionpercapita_data_file.to_csv("output/econ_allconsumption.csv", index=False, header=True)
allpersonalconsumptionpercapita_data_file.dtypes
allpersonalconsumptionpercapita_data_file

                   state     2015     2016     2017     2018
0          United States  38278.0  39440.0  40922.0  42757.0
1                Alabama  30843.0  31497.0  32527.0  33904.0
2                 Alaska  45345.0  46205.0  48053.0  50246.0
3                Arizona  32438.0  33059.0  34471.0  35906.0
4               Arkansas  30596.0  31628.0  32913.0  34095.0
5             California  40743.0  42549.0  44502.0  46981.0
6               Colorado  39268.0  40552.0  42215.0  44174.0
7            Connecticut  47998.0  49215.0  50893.0  52941.0
8               Delaware  40573.0  41416.0  42536.0  44103.0
9   District of Columbia  57567.0  58795.0  60471.0  63151.0
10               Florida  37700.0  38447.0  39539.0  41148.0
11               Georgia  32858.0  33788.0  34965.0  36488.0
12                Hawaii  42258.0  44001.0  46279.0  48759.0
13                 Idaho  32472.0  33761.0  35322.0  36777.0
14              Illinois  39835.0  41213.0  42979.0  45085.0
15               Indiana  33797.0  34832.0  36354.0  37680.0
16                  Iowa  35361.0  36361.0  37706.0  38944.0
17                Kansas  34439.0  35324.0  36478.0  37897.0
18              Kentucky  31696.0  32720.0  33828.0  35150.0
19             Louisiana  33062.0  33713.0  34696.0  36104.0
20                 Maine  40809.0  41836.0  43436.0  45497.0
21              Maryland  42252.0  43593.0  45207.0  46820.0
22         Massachusetts  49725.0  51292.0  53286.0  55095.0
23              Michigan  36607.0  37795.0  39118.0  40764.0
24             Minnesota  41887.0  43397.0  45439.0  47434.0
25           Mississippi  28434.0  29109.0  29942.0  31083.0
26              Missouri  36384.0  37291.0  38618.0  40060.0
27               Montana  38189.0  39236.0  40933.0  42698.0
28              Nebraska  37610.0  38831.0  40190.0  41690.0
29                Nevada  38220.0  39074.0  39997.0  41458.0
30         New Hampshire  47201.0  48335.0  50034.0  52120.0
31            New Jersey  47694.0  49047.0  50541.0  52729.0
32            New Mexico  32975.0  33757.0  34687.0  36258.0
33              New York  45833.0  47668.0  49857.0  52701.0
34        North Carolina  31903.0  32856.0  34179.0  35718.0
35          North Dakota  46342.0  45871.0  46814.0  48499.0
36                  Ohio  37137.0  38040.0  39341.0  40852.0
37              Oklahoma  31602.0  32167.0  32966.0  34500.0
38                Oregon  38021.0  39160.0  40870.0  42717.0
39          Pennsylvania  40239.0  41316.0  42760.0  44805.0
40          Rhode Island  40889.0  41893.0  43266.0  45144.0
41        South Carolina  31853.0  32726.0  33637.0  34689.0
42          South Dakota  39689.0  40961.0  42491.0  44149.0
43             Tennessee  32491.0  33539.0  34886.0  36340.0
44                 Texas  35302.0  36134.0  37396.0  39045.0
45                  Utah  33009.0  34483.0  35801.0  37721.0
46               Vermont  45333.0  46429.0  47882.0  49950.0
47              Virginia  40843.0  42085.0  43457.0  45139.0
48            Washington  41120.0  42427.0  44235.0  46574.0
49         West Virginia  32516.0  33489.0  34604.0  36071.0
50             Wisconsin  37896.0  39152.0  40611.0  42456.0
51               Wyoming  39423.0  39604.0  40921.0  42766.0

In [6]:
#Median Income to DataFrame (note:measure in dollars)

In [11]:
#Health Care Consumption Per Capita to DataFrame (note:measure in dollars)
file = "Resources/ALL/data/personalconsumptionpercapita1997_2018.csv"
personalconsumptionpercapita_data_file_all = pd.read_csv(file)
health_personalconsumptionpercapita_data_file = personalconsumptionpercapita_data_file_all.copy()
num_of_indexes = int(health_personalconsumptionpercapita_data_file["GeoName"].count())
indexes = []
health_personalconsumptionpercapita_data_file = health_personalconsumptionpercapita_data_file.rename(columns={"GeoName":"state"})
for index in range(num_of_indexes):
    if health_personalconsumptionpercapita_data_file.loc[index,"Description"] == "   Health care":
        indexes.append(index)
health_personalconsumptionpercapita_data_file = health_personalconsumptionpercapita_data_file.iloc[indexes]
health_personalconsumptionpercapita_data_file = health_personalconsumptionpercapita_data_file.reset_index()
health_personalconsumptionpercapita_data_file = health_personalconsumptionpercapita_data_file.iloc[:52]
health_personalconsumptionpercapita_data_file = health_personalconsumptionpercapita_data_file.loc[:,years]
for year in years:
    try:
        gdp_data_file[year] = gdp_data_file[year].astype(np.float64)
    except ValueError:
        None

health_personalconsumptionpercapita_data_file.to_csv("output/econ_health_consumption.csv", index=False, header=True)
health_personalconsumptionpercapita_data_file.dtypes
health_personalconsumptionpercapita_data_file

                   state    2015     2016     2017     2018
0          United States  6414.0   6686.0   6900.0   7191.0
1                Alabama  5485.0   5619.0   5806.0   6019.0
2                 Alaska  9607.0  10020.0  10730.0  11531.0
3                Arizona  5169.0   5329.0   5584.0   5851.0
4               Arkansas  5413.0   5762.0   6048.0   6299.0
5             California  6408.0   6838.0   7129.0   7543.0
6               Colorado  6046.0   6334.0   6413.0   6568.0
7            Connecticut  7308.0   7499.0   7599.0   7889.0
8               Delaware  7943.0   8205.0   8427.0   8710.0
9   District of Columbia  9673.0   9735.0   9885.0  10150.0
10               Florida  6393.0   6569.0   6703.0   6925.0
11               Georgia  5316.0   5582.0   5743.0   6061.0
12                Hawaii  6031.0   6441.0   6842.0   7264.0
13                 Idaho  5607.0   5923.0   6116.0   6424.0
14              Illinois  6545.0   6836.0   7054.0   7441.0
15               Indiana  6875.0   7273.0   7690.0   7957.0
16                  Iowa  6111.0   6325.0   6431.0   6564.0
17                Kansas  6091.0   6189.0   6352.0   6592.0
18              Kentucky  6044.0   6319.0   6477.0   6720.0
19             Louisiana  6129.0   6362.0   6427.0   6623.0
20                 Maine  7217.0   7420.0   7628.0   7935.0
21              Maryland  6993.0   7235.0   7446.0   7683.0
22         Massachusetts  8547.0   8902.0   9111.0   9159.0
23              Michigan  6386.0   6675.0   6788.0   7031.0
24             Minnesota  7503.0   7849.0   8184.0   8615.0
25           Mississippi  5673.0   5822.0   5957.0   6231.0
26              Missouri  6511.0   6769.0   7009.0   7279.0
27               Montana  6605.0   6974.0   7346.0   7581.0
28              Nebraska  6599.0   6934.0   7154.0   7449.0
29                Nevada  5153.0   5424.0   5636.0   5948.0
30         New Hampshire  7912.0   8260.0   8529.0   8906.0
31            New Jersey  6849.0   7111.0   7288.0   7591.0
32            New Mexico  5779.0   6108.0   6213.0   6448.0
33              New York  7174.0   7571.0   7957.0   8551.0
34        North Carolina  5581.0   5779.0   6100.0   6393.0
35          North Dakota  7896.0   8174.0   8445.0   8700.0
36                  Ohio  7024.0   7281.0   7428.0   7685.0
37              Oklahoma  5804.0   5935.0   5997.0   6254.0
38                Oregon  6561.0   6834.0   7087.0   7320.0
39          Pennsylvania  7236.0   7478.0   7717.0   8073.0
40          Rhode Island  7199.0   7280.0   7360.0   7510.0
41        South Carolina  5592.0   5761.0   5827.0   5882.0
42          South Dakota  8053.0   8406.0   8820.0   9154.0
43             Tennessee  6010.0   6099.0   6299.0   6477.0
44                 Texas  5585.0   5798.0   5947.0   6098.0
45                  Utah  4720.0   5057.0   5129.0   5289.0
46               Vermont  8130.0   8488.0   8639.0   9076.0
47              Virginia  5968.0   6207.0   6386.0   6624.0
48            Washington  6870.0   7141.0   7420.0   7779.0
49         West Virginia  7154.0   7494.0   7847.0   8254.0
50             Wisconsin  7261.0   7520.0   7729.0   8097.0
51               Wyoming  6391.0   6451.0   6567.0   6722.0

In [10]:
#Health Care to Personal Consumption Ratio Per Capita to DataFrame 
health_personal_consumptionratio = health_personalconsumptionpercapita_data_file["state"]
health_personal_consumptionratio = pd.DataFrame(health_personal_consumptionratio)
for year in years:
    try:
        total = allpersonalconsumptionpercapita_data_file[year]
        health = health_personalconsumptionpercapita_data_file[year]
        health_personal_consumptionratio[year] = 100*health/total
    except TypeError:
        None

health_personal_consumptionratio
health_personal_consumptionratio.to_csv("output/econ_health_consumptionratio.csv", index=False, header=True)

health_personal_consumptionratio

                   state       2015       2016       2017       2018
0          United States  16.756361  16.952333  16.861346  16.818299
1                Alabama  17.783614  17.839794  17.849786  17.753067
2                 Alaska  21.186459  21.685965  22.329511  22.949090
3                Arizona  15.935014  16.119665  16.199124  16.295327
4               Arkansas  17.691855  18.218035  18.375718  18.474850
5             California  15.727855  16.070883  16.019505  16.055427
6               Colorado  15.396761  15.619452  15.191283  14.868475
7            Connecticut  15.225634  15.237224  14.931327  14.901494
8               Delaware  19.577059  19.811184  19.811454  19.749223
9   District of Columbia  16.803030  16.557530  16.346679  16.072588
10               Florida  16.957560  17.085858  16.952882  16.829494
11               Georgia  16.178708  16.520658  16.424996  16.610941
12                Hawaii  14.271854  14.638304  14.784243  14.897762
13                 Idaho  17.267184  17.543912  17.314988  17.467439
14              Illinois  16.430275  16.586999  16.412667  16.504381
15               Indiana  20.342042  20.880225  21.153106  21.117304
16                  Iowa  17.281751  17.395011  17.055641  16.854971
17                Kansas  17.686344  17.520666  17.413235  17.394517
18              Kentucky  19.068652  19.312347  19.146861  19.118065
19             Louisiana  18.537898  18.871059  18.523749  18.344228
20                 Maine  17.684824  17.735921  17.561470  17.440710
21              Maryland  16.550696  16.596701  16.470901  16.409654
22         Massachusetts  17.188537  17.355533  17.098300  16.624013
23              Michigan  17.444751  17.661066  17.352625  17.248062
24             Minnesota  17.912479  18.086504  18.010960  18.162078
25           Mississippi  19.951467  20.000687  19.895131  20.046328
26              Missouri  17.895229  18.151833  18.149568  18.170245
27               Montana  17.295556  17.774493  17.946400  17.754930
28              Nebraska  17.545865  17.856867  17.800448  17.867594
29                Nevada  13.482470  13.881353  14.091057  14.347050
30         New Hampshire  16.762357  17.089066  17.046408  17.087490
31            New Jersey  14.360297  14.498338  14.419976  14.396253
32            New Mexico  17.525398  18.094025  17.911610  17.783662
33              New York  15.652477  15.882773  15.959645  16.225499
34        North Carolina  17.493653  17.588873  17.847216  17.898539
35          North Dakota  17.038540  17.819537  18.039475  17.938514
36                  Ohio  18.913752  19.140379  18.881066  18.811808
37              Oklahoma  18.365926  18.450586  18.191470  18.127536
38                Oregon  17.256253  17.451481  17.340347  17.136035
39          Pennsylvania  17.982554  18.099526  18.047240  18.018078
40          Rhode Island  17.606202  17.377605  17.011048  16.635655
41        South Carolina  17.555646  17.603740  17.323186  16.956384
42          South Dakota  20.290257  20.521960  20.757337  20.734331
43             Tennessee  18.497430  18.184800  18.055954  17.823335
44                 Texas  15.820633  16.045829  15.902770  15.617877
45                  Utah  14.299131  14.665197  14.326415  14.021367
46               Vermont  17.933955  18.281677  18.042271  18.170170
47              Virginia  14.612051  14.748723  14.694986  14.674672
48            Washington  16.707198  16.831263  16.774048  16.702452
49         West Virginia  22.001476  22.377497  22.676569  22.882648
50             Wisconsin  19.160334  19.207192  19.031789  19.071509
51               Wyoming  16.211349  16.288759  16.047995  15.718094

In [ ]:
#Health Care to Personal Consumption Ratio Per Capita to DataFrame 
health_personal_consumptionratio = health_personalconsumptionpercapita_data_file["state"]
health_personal_consumptionratio = pd.DataFrame(health_personal_consumptionratio)
for year in years:
    try:
        total = allpersonalconsumptionpercapita_data_file[year]
        health = health_personalconsumptionpercapita_data_file[year]
        health_personal_consumptionratio[year] = 100*health/total
    except TypeError:
        None

health_personal_consumptionratio
health_personal_consumptionratio.to_csv("output/econ_health_consumptionratio.csv", index=False, header=True)

health_personal_consumptionratio