In [2]:
import pandas as pd
import numpy as np
start_year = 2015

In [9]:
#Creating Language DataFrame
language_file2015 = 'Resources/2015/data/language_2015.csv'
language_file2016 = 'Resources/2016/data/language_2016.csv'
language_file2017 = 'Resources/2017/data/language_2017.csv'
language_file2018 = 'Resources/2018/data/language_2018.csv'

language_2015 = pd.read_csv(language_file2015)
language_2016 = pd.read_csv(language_file2016)
language_2017 = pd.read_csv(language_file2017)
language_2018 = pd.read_csv(language_file2018)

language_2015 = pd.DataFrame(language_2015)
language_2016 = pd.DataFrame(language_2016)
language_2017 = pd.DataFrame(language_2017)
language_2018 = pd.DataFrame(language_2018)

language_datas = [language_2015, language_2016, language_2017, language_2018]

spanish_household_data = language_2015.copy()
spanish_household_data = spanish_household_data.loc[:,["GEO_ID","NAME"]]
spanish_household_data = spanish_household_data.rename(columns={"NAME":"State"})

spanish_only_data = language_2015.copy()
spanish_only_data = spanish_only_data.loc[:,["GEO_ID","NAME"]]
spanish_only_data = spanish_only_data.rename(columns={"NAME":"State"})

language_data_labels =["NAME","S1602_C02_002E","S1602_C04_002E",]
year = start_year
for data in language_datas: 
    data = data[language_data_labels]
    for x in range(len(language_data_labels)):
        if x > 0:
            try:
                data.iloc[:,x] = pd.to_numeric(data.iloc[:,x])
            except ValueError:
                None
    data = data.rename(columns={language_data_labels[0]:"State",
                                language_data_labels[1]:"{}".format(year),
                                language_data_labels[2]:"{}".format(year)})
    spanish_household_data = pd.merge(spanish_household_data, data.iloc[:,[0,1]], on="State")
    spanish_only_data = pd.merge(spanish_only_data, data.iloc[:,[0,2]], on="State")
    year += 1
spanish_household_data = spanish_household_data.iloc[1:,1:]
spanish_household_data.to_csv("output/pop_spanish_household.csv", index=False, header=True)
spanish_only_data = spanish_only_data.iloc[1:,1:]
spanish_only_data.to_csv("output/pop_spanish_only.csv", index=False, header=True)
spanish_household_data

                   State  2015  2016  2017  2018
1                Alabama   3.2   3.0   3.0   3.2
2                 Alaska   5.1   4.5   4.3   4.6
3                Arizona  19.6  19.5  19.8  20.1
4               Arkansas   4.6   4.8   4.8   5.1
5             California  25.8  25.8  25.9  26.2
6               Colorado  11.8  11.8  11.5  11.5
7            Connecticut  12.1  12.3  12.2  12.6
8               Delaware   7.2   6.6   6.9   6.2
9   District of Columbia   9.4   9.2   8.5   8.4
10               Florida  20.2  20.1  20.6  21.3
11               Georgia   7.3   7.2   7.5   7.5
12                Hawaii     3   3.1   3.4   3.7
13                 Idaho   7.2   7.7   8.3   8.4
14              Illinois  11.4  11.6  11.7  11.9
15               Indiana   4.5   4.7   4.7   4.8
16                  Iowa   3.9   4.1   3.8   4.1
17                Kansas     7   6.9   7.5   7.6
18              Kentucky   2.8   2.8   2.9   2.9
19             Louisiana   3.9   4.2   4.5   4.0
20                 Maine   1.2   1.4   1.2   1.1
21              Maryland   6.9   7.4   7.4   7.5
22         Massachusetts   8.5   9.2   9.1   9.5
23              Michigan   3.2   3.1   3.2   3.2
24             Minnesota   3.7   3.7   3.5   3.8
25           Mississippi   2.6   2.7   2.2   2.5
26              Missouri   2.8   2.9   2.9   2.8
27               Montana   1.9   1.7   2.4   2.5
28              Nebraska   6.7   6.8   7.6   6.8
29                Nevada  18.8  19.1  19.2  19.6
30         New Hampshire   2.2   2.5   2.5   3.0
31            New Jersey  15.6  15.8  16.0  16.2
32            New Mexico    31  30.1  30.5  31.0
33              New York  14.6  14.5  14.8  14.8
34        North Carolina   6.7   6.7   6.9   6.9
35          North Dakota   2.1   2.0   2.3   2.7
36                  Ohio   2.7   2.6   2.7   2.8
37              Oklahoma   6.5   6.6   6.5   6.9
38                Oregon   8.2   8.0   7.9   8.5
39          Pennsylvania   4.8   5.1   5.3   5.5
40          Rhode Island  11.3  10.8  11.6  11.7
41        South Carolina   4.2   4.2   4.7   4.7
42          South Dakota   2.8   2.2   2.5   2.6
43             Tennessee   3.6   4.1   3.8   4.1
44                 Texas  28.6  29.2  28.9  29.0
45                  Utah  11.1  11.1  11.4  12.0
46               Vermont   1.6   1.3   1.4   1.6
47              Virginia   6.5   6.7   6.7   7.0
48            Washington   7.7   7.5   7.7   7.9
49         West Virginia   1.4   1.4   1.2   1.5
50             Wisconsin   4.7   4.6   4.5   4.7
51               Wyoming   5.1   5.7   6.2   5.8
52           Puerto Rico  95.4  95.3  95.0  95.3

In [11]:
#Creating Proverty DataFrame
poverty_file2015 = 'Resources/2015/data/poverty_2015.csv'
poverty_file2016 = 'Resources/2016/data/poverty_2016.csv'
poverty_file2017 = 'Resources/2017/data/poverty_2017.csv'
poverty_file2018 = 'Resources/2018/data/poverty_2018.csv'

poverty_2015 = pd.read_csv(poverty_file2015)
poverty_2016 = pd.read_csv(poverty_file2016)
poverty_2017 = pd.read_csv(poverty_file2017)
poverty_2018 = pd.read_csv(poverty_file2018)

poverty_2015 = pd.DataFrame(poverty_2015)
poverty_2016 = pd.DataFrame(poverty_2016)
poverty_2017 = pd.DataFrame(poverty_2017)
poverty_2018 = pd.DataFrame(poverty_2018)

poverty_datas = [poverty_2015, poverty_2016, poverty_2017, poverty_2018]
poverty_data_all = poverty_2015.copy()
poverty_data_all = poverty_data_all.loc[:,["GEO_ID","NAME"]]
poverty_data_all = poverty_data_all.rename(columns={"NAME":"State"})
poverty_data_labels = ["NAME","S1701_C03_001E"]

year = start_year
for data in poverty_datas: 
    data = data[poverty_data_labels]
    for x in range(len(poverty_data_labels)):
        if x > 0:
            try:
                data.iloc[:,x] = pd.to_numeric(data.iloc[:,x])
            except ValueError:
                None
    data = data.rename(columns={poverty_data_labels[0]:"State",
                                poverty_data_labels[1]:"{}".format(year)})
    poverty_data_all = pd.merge(poverty_data_all, data, on="State")
    year += 1
poverty_data_all_final = poverty_data_all.iloc[1:,1:]
poverty_data_all_final.to_csv("output/pop_poverty.csv", index=False, header=True)
poverty_data_all_final

                   State  2015  2016  2017  2018
1                Alabama  18.5  17.1  16.9  16.8
2                 Alaska  10.3   9.9  11.1  10.9
3                Arizona  17.4  16.4  14.9  14.0
4               Arkansas  19.1  17.2  16.4  17.2
5             California  15.3  14.3  13.3  12.8
6               Colorado  11.5  11.0  10.3   9.6
7            Connecticut  10.5   9.8   9.6  10.4
8               Delaware  12.4  11.7  13.6  12.5
9   District of Columbia  17.3  18.6  16.6  16.2
10               Florida  15.7  14.7  14.0  13.6
11               Georgia    17  16.0  14.9  14.3
12                Hawaii  10.6   9.3   9.5   8.8
13                 Idaho  15.1  14.4  12.8  11.8
14              Illinois  13.6  13.0  12.6  12.1
15               Indiana  14.5  14.1  13.5  13.1
16                  Iowa  12.2  11.8  10.7  11.2
17                Kansas    13  12.1  11.9  12.0
18              Kentucky  18.5  18.5  17.2  16.9
19             Louisiana  19.6  20.2  19.7  18.6
20                 Maine  13.4  12.5  11.1  11.6
21              Maryland   9.7   9.7   9.3   9.0
22         Massachusetts  11.5  10.4  10.5  10.0
23              Michigan  15.8  15.0  14.2  14.1
24             Minnesota  10.2   9.9   9.5   9.6
25           Mississippi    22  20.8  19.8  19.7
26              Missouri  14.8  14.0  13.4  13.2
27               Montana  14.6  13.3  12.5  13.0
28              Nebraska  12.6  11.4  10.8  11.0
29                Nevada  14.7  13.8  13.0  12.9
30         New Hampshire   8.2   7.3   7.7   7.6
31            New Jersey  10.8  10.4  10.0   9.5
32            New Mexico  20.4  19.8  19.7  19.5
33              New York  15.4  14.7  14.1  13.6
34        North Carolina  16.4  15.4  14.7  14.0
35          North Dakota    11  10.7  10.3  10.7
36                  Ohio  14.8  14.6  14.0  13.9
37              Oklahoma  16.1  16.3  15.8  15.6
38                Oregon  15.4  13.3  13.2  12.6
39          Pennsylvania  13.2  12.9  12.5  12.2
40          Rhode Island  13.9  12.8  11.6  12.9
41        South Carolina  16.6  15.3  15.4  15.3
42          South Dakota  13.7  13.3  13.0  13.1
43             Tennessee  16.7  15.8  15.0  15.3
44                 Texas  15.9  15.6  14.7  14.9
45                  Utah  11.3  10.2   9.7   9.0
46               Vermont  10.2  11.9  11.3  11.0
47              Virginia  11.2  11.0  10.6  10.7
48            Washington  12.2  11.3  11.0  10.3
49         West Virginia  17.9  17.9  19.1  17.8
50             Wisconsin  12.1  11.8  11.3  11.0
51               Wyoming  11.1  11.3  11.3  11.1
52           Puerto Rico  46.1  43.5  44.4  43.1

In [28]:
#Age Demographic Dataset
age_file2015 = 'Resources/2015/data/age_2015.csv'
age_file2016 = 'Resources/2016/data/age_2016.csv'
age_file2017 = 'Resources/2017/data/age_2017.csv'
age_file2018 = 'Resources/2018/data/age_2018.csv'

age_2015 = pd.read_csv(age_file2015)
age_2016 = pd.read_csv(age_file2016)
age_2017 = pd.read_csv(age_file2017)
age_2018 = pd.read_csv(age_file2018)

age_2015 = pd.DataFrame(age_2015)
age_2016 = pd.DataFrame(age_2016)
age_2017 = pd.DataFrame(age_2017)
age_2018 = pd.DataFrame(age_2018)

age_datas = [age_2015, age_2016, age_2017, age_2018]
age_under18_data = age_2015.copy()
age_under18_data = age_under18_data.loc[:,["GEO_ID","NAME"]]
age_under18_data = age_under18_data.rename(columns={"NAME":"State"})
age_18to64_data = age_2015.copy()
age_18to64_data = age_18to64_data.loc[:,["GEO_ID","NAME"]]
age_18to64_data = age_18to64_data.rename(columns={"NAME":"State"})
age_65andup_data = age_2015.copy()
age_65andup_data = age_65andup_data.loc[:,["GEO_ID","NAME"]]
age_65andup_data = age_65andup_data.rename(columns={"NAME":"State"})


year = start_year
for data in age_datas: 
    if year > 2016:
        data = data.iloc[1:,1:]
        age_data_used = ["S0101_C02_022E","S0101_C02_026E","S0101_C02_030E"]
        age_data_labels = ["NAME","S0101_C02_022E","18-64","S0101_C02_030E"]
        for column in age_data_used:
            try:
                data[column] = pd.to_numeric(data[column])
            except ValueError:
                None
        data["18-64"]=data["S0101_C02_026E"]-data["S0101_C02_030E"]
    else:
        data = data.iloc[1:,1:]
        data = data.reset_index(drop=True)
        age_data_used = ["S0101_C01_001E","S0101_C01_002E","S0101_C01_020E","S0101_C01_021E","S0101_C01_025E","S0101_C01_028E"]
        for column in age_data_used:
            try:
                data[column] = pd.to_numeric(data[column])
            except ValueError:
                None
        age_data_labels = ["NAME","under 18","18-64","65 and up"]
        data["under 18"] = (data["S0101_C01_002E"]+data["S0101_C01_020E"]+data["S0101_C01_021E"])
        data["18-64"] = (data["S0101_C01_025E"]-data["S0101_C01_028E"])
        data["65 and up"]  = data["S0101_C01_028E"]
    data = data[age_data_labels]
    data = data.rename(columns={age_data_labels[0]:"State",
                                age_data_labels[1]:"{}".format(year),
                                age_data_labels[2]:"{}".format(year),
                                age_data_labels[3]:"{}".format(year)})
    age_under18_data = pd.merge(age_under18_data, data.iloc[:,[0,1]], on="State")
    age_18to64_data = pd.merge(age_18to64_data, data.iloc[:,[0,2]], on="State")
    age_65andup_data = pd.merge(age_65andup_data, data.iloc[:,[0,3]], on="State")
    year += 1


age_under18_data = age_under18_data.iloc[:,1:]
age_under18_data = age_under18_data.reset_index(drop=True)
age_18to64_data = age_18to64_data.iloc[:,1:]
age_18to64_data = age_18to64_data.reset_index(drop=True)
age_65andup_data = age_65andup_data.iloc[:,1:]
age_65andup_data = age_65andup_data.reset_index(drop=True)

age_under18_data.to_csv("output/pop_age_under18.csv", index=False, header=True)
age_18to64_data.to_csv("output/pop_age_18to64_data.csv", index=False, header=True)
age_65andup_data.to_csv("output/pop_age_65andup.csv", index=False, header=True)